### PR TITLE
[fix] Fix map icon tooltips not showing multiple objectives

### PR DESCRIPTION
**Pull request by BreakBB**
## Issue references

Fixes #

## Proposed changes

-
-

## Screenshots

Before:
image

With the fix:
image

### CODE REVIEW

**Comment by Cabro** [comment]
Seems to be working, now i see multiple objectives on the world map
image

In your example, is there a way to make it show both Meat and Skin on the same NPC source without adding a new line for each objective?

**Comment by BreakBB** [comment]
> In your example, is there a way to make it show both Meat and Skin on the same NPC source without adding a new line for each objective? Just make it show as it shows on the creature tooltip itself?

It wasn't like that before, was it? I mean Questie always had it on seperate lines, right?

**Comment by Cabro** [comment]
> It wasn't like that before, was it? I mean Questie always had it on seperate lines, right?

I am not certain of anything anymore :D

**Comment by MyTechnoHunter** [comment]
As far as I know we've always had objectives On Their Own Line I don't think we ever combined them

**Comment by BreakBB** [comment]
> As far as I know we've always had objectives On Their Own Line I don't think we ever combined them

I think so too 😅

**Comment by Cabro** [comment]
I am not sure what is happening here, if it's related to this PR or not, but:

image

The objective is in the form of object + custom text linked to it, and it doesn't pick up the object itself.

`[questKeys.objectives] = {nil,{{400062,"Test the Eggscilliscope Prototype"}}},`

**Comment by MyTechnoHunter** [comment]
er, i am confused.. wht seems to be the issue? that its not showing rookery egg?

**Comment by Cabro** [comment]
> er, i am confused.. wht seems to be the issue? that its not showing rookery egg?

image

**Comment by MyTechnoHunter** [comment]
and egg freezing isnt the quest name?

still confused

**Comment by Cabro** [comment]
Just like... every other quest in that list has a source for the objective, such as "Halycon", "Spire Spider Egg" etc,  the first quest is missing it. It should be another line between the quest name "[60+] Egg Freezing (4734)" and the objective "Test the Eggscilliscope Prototype" with the source of the objective - "Rookery Egg"

**Comment by MyTechnoHunter** [comment]
where is the custom object referenced.. does it have a valid entry to show? nothing goofy like spaces, or not being in the relevant section of the DB?

**Comment by Cabro** [comment]
```
        [4734] = {
            [questKeys.objectives] = {nil,{{400062,"Test the Eggscilliscope Prototype"}}},
        },
```

**Comment by MyTechnoHunter** [comment]
is that code you added? i dont see it when i search my questie?

**Comment by MyTechnoHunter** [comment]
and that makes no sense.. the comment claims its in upper blackrock spire.. and the zone says lower?

**Comment by Cabro** [comment]
And an addendum to the previous comment: all those NPCs listed in the image above have different spawn points, with different quest icons on the map. I found a case where if you have mobs with the exact same spawn coords, only 1 of them gets listed: 
image

There should be 4 NPCs that drop it: Earthen, Hoary, Azure and Crimson. 

In my classicNPCFixes.lua correction file i put this:
```
        [15209] = {
            [npcKeys.zoneID] = zoneIDs.SILITHUS,
            [npcKeys.spawns] = {[zoneIDs.SILITHUS] = {{37.3,44.8},{38.29,46.46},{24.44,36.00},{27.93,30.62},{20.46,86.16},{18.23,81.12}}},
        },
        [15211] = {
            [npcKeys.zoneID] = zoneIDs.SILITHUS,
            [npcKeys.spawns] = {[zoneIDs.SILITHUS] = {{37.3,44.8},{38.29,46.46},{24.44,36.00},{27.93,30.62},{20.46,86.16},{18.23,81.12}}},
        },
        [15212] = {
            [npcKeys.zoneID] = zoneIDs.SILITHUS,
            [npcKeys.spawns] = {[zoneIDs.SILITHUS] = {{37.3,44.8},{38.29,46.46},{24.44,36.00},{27.93,30.62},{20.46,86.16},{18.23,81.12}}},
        },
        [15307] = {
            [npcKeys.zoneID] = zoneIDs.SILITHUS,
            [npcKeys.spawns] = {[zoneIDs.SILITHUS] = {{37.3,44.8},{38.29,46.46},{24.44,36.00},{27.93,30.62},{20.46,86.16},{18.23,81.12}}},
        },
```
And it only shows one of the 4 as source.

**Comment by BreakBB** [comment]
> Back to this PR. Since it can already group multiple sources, why not group multiple objectives? :)

I will take another look into the code, to see if I can understand how/where that is done.

> And it only shows one of the 4 as source. Could this be because when the map icon was created, only 1 npc was linked to it? Maybe the issue is in the map icon creation?
>
> LE: Earthen Templar has the highest ID of the 4 NPCs, 15307, so most likely it is updating (as in replacing) the other NPCs tooltips for this map icon.

It can indeed be, that the last ID overrides the others. Might be the code currently uses an ID which is always the same 🤔 Need to verify that in the code.

**Comment by BreakBB** [comment]
@Cabro this should be fixed with the last commit:

> Back to this PR. Since it can already group multiple sources, why not group multiple objectives? :)

**Pull request merged**
