### PR TITLE
[quest] 27348 Secure the Cargo! added

### LINKED ISSUE #6478: Quest 27348 Secure the Cargo! showing as available when it is not
### Description

https://www.wowhead.com/cata/quest=27348/secure-the-cargo

Required prequest is named 27346 The Zeppelin Crash. After completing it, this quest also showed up.

https://www.wowhead.com/cata/quest=27346/the-zeppelin-crash

WoWScrnShot_100624_143521
WoWScrnShot_100624_143535

### Questie version

v10.5.1

### Game flavor

Cata

### PR DESCRIPTION
**Pull request by TorpedoCXC**
Added prerequisite quest 27346 The Zeppelin Crash

## Issue references

Fixes #6478

### CODE REVIEW

**Comment by coldpasta123** [comment]
I don't think this is correct - I have not completed The Zeppelin Crash but I have completed Secure the Cargo. Whilst this might seem like a data correction in this example, I think it will make it incorrect in others.

From my own experience, and reading comments on various related wowhead quests, I think there might be a few prerequisites of which any one needs be completed. The Zeppelin Crash is one and I think there is at least one more, which I suspect is a pre-Cata quest but haven't worked out which yet.

**Comment by TorpedoCXC** [comment]
@coldpasta123 You are probably right. There may be multiple prerequisite quests that allow doing 27348.

**Comment by TorpedoCXC** [comment]
So, this
```
[27348] = { -- Secure the Cargo!
            [questKeys.preQuestSingle] = {27346},
        },
```

should become this?
```
[27348] = { -- Secure the Cargo!
            [questKeys.preQuestGroup] = {27346}, -- TODO: Add missing quests, there seem to be more.
        },
```

How can we find out which prerequisite quests are valid for this?

**Comment by BreakBB** [comment]
> How can we find out which prerequisite quests are valid for this?

That's the fun part about pre-quest related fixes... You need to test it out ingame 🙈

**Comment by coldpasta123** [comment]
> So, this
> 
> ```
> [27348] = { -- Secure the Cargo!
>             [questKeys.preQuestSingle] = {27346},
>         },
> ```
> 
> should become this?
> 
> ```
> [27348] = { -- Secure the Cargo!
>             [questKeys.preQuestGroup] = {27346}, -- TODO: Add missing quests, there seem to be more.
>         },
> ```
> 
> How can we find out which prerequisite quests are valid for this?

@TorpedoCXC if we add 27346 as a prequest, Secure the Cargo would not appear for anyone who has not completed The Zeppelin Crash, which we know is incorrect logic. I think it makes more sense not to change it until we work out the missing information.

**Comment by coldpasta123** [comment]
Wondering if it might be this: https://www.wowhead.com/cata/quest=1187/razzerics-tweaking

**Comment by TorpedoCXC** [comment]
> > So, this
> > ```
> > [27348] = { -- Secure the Cargo!
> >             [questKeys.preQuestSingle] = {27346},
> >         },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should become this?
> > ```
> > [27348] = { -- Secure the Cargo!
> >             [questKeys.preQuestGroup] = {27346}, -- TODO: Add missing quests, there seem to be more.
> >         },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How can we find out which prerequisite quests are valid for this?
> 
> @TorpedoCXC if we add 27346 as a prequest, Secure the Cargo would not appear for anyone who has not completed The Zeppelin Crash, which we know is incorrect logic. I think it makes more sense not to change it until we work out the missing information.

You are right. As long as we don't have a complete list of all possible prerequisite quests, we should not do any changes. But if I understood the logix behind the Questie database, `preQuestGroup` should be the correct attribute to set, right?

**Comment by BreakBB** [comment]
> But if I understood the logic behind the Questie database, preQuestGroup should be the correct attribute to set, right?

Yes, `preQuestGroup` is used when **all** quests in that list needs to be complete to accept the quest. While `preQuestSingle` means **any** quest in that list.

**Comment by TorpedoCXC** [comment]
@BreakBB If this is true, then `preQuestSingle` should be the correct attribute to set, as you only need to have completed either 27346 or the quest @coldpasta123 is refering to, to make 27348 available. I will update my above comment.

**Comment by BreakBB** [comment]
> @BreakBB If this is true, then `preQuestSingle` should be the correct attribute to set, as you only need to have completed either 27346 or the quest @coldpasta123 is refering to, to make 27348 available. I will update my above comment.

Unfortunately not, because you don't need to complete either quest to make it available.

**Comment by TorpedoCXC** [comment]
> 
> Unfortunately not, because you don't need to complete either quest to make it available.

According to my and @coldpasta123 experience, 27348 Secure the Cargo! is not available until you either complete 27346 The Zeppelin Crash or another (yet unknown) prequest. He suspects https://www.wowhead.com/cata/quest=1187/razzerics-tweaking being the quest.

**Comment by BreakBB** [comment]
Oh wow, I mixed the issues up, my bad! 😅 

Yeah, if you only need one of these two, then `preQuestSingle` is correct to be used 👍🏻

**Pull request closed without merging**
