### PR TITLE
Fix item Gyrochronatom (4389)

### PR DESCRIPTION
**Pull request by gouletr**
Fix item [Gyrochronatom (4389)](https://classic.wowhead.com/item=4389/gyrochronatom) missing just about all information about it.

### CODE REVIEW

**Comment by BreakBB** [comment]
I wouldn't want to add the NPCs for this as well. Otherwise users on the related quest will be confused and might head to Stranglethorn for the NPCs.

**Comment by gouletr** [comment]
Those NPCs do drop that item thought, isn't better if the database is 100% accurate? However I can understand your reluctance, since the drop rate is so low anyway. I'll just remove the NPCs for now.

**Comment by drejjmit** [comment]
I thought the vendors were limited supply 🤔

**Comment by gouletr** [comment]
> I thought the vendors were limited supply 🤔

Sure, but why not show them on the map nonetheless? It's the same for `Bronze Tube` and I've used multiple vendors exactly for that purpose.

What is Questie trying to achieve here? Isn't accuracy important just as much?

**Comment by BreakBB** [comment]
I am with your on the vendors @gouletr 👍🏻  But yeah if the drop chance on NPCs is too low we don't show them as that won't be very helpful in most cases. Limited supply vendors are a good chance imo.

**Pull request merged**
