### PR TITLE
[quest] Fix reputation gain from "The Crown of Will"

### PR DESCRIPTION
**Pull request by danez**
## Issue references

Fixes #

## Proposed changes

- The quest gives reputation with undercity not Orgrimmar, see also https://www.wowhead.com/classic/quest=518/the-crown-of-will
-

## Screenshots
Screenshot 2023-12-29 at 13 27 17

### CODE REVIEW

**Comment by danez** [comment]
Okay I changed it.

**Comment by BreakBB** [comment]
Awesome, thank you!

**Comment by danez** [comment]
To be fair though, most of the reputation on quests is wrong. At first I thought it is due to level scaling, but even when the quest is my level it is usually wrong.

**Comment by BreakBB** [comment]
Yeah, you are absolutely right. There are lot of vanilla quests with wrong reputation values 🙈 

I opened up an issue, maybe we'll have time for it #5384

**Pull request merged**
