### PR TITLE
Update QuestieEventHandler.lua

### PR DESCRIPTION
**Pull request by Duugu**
Fix for https://github.com/Questie/Questie/issues/2995

### CODE REVIEW

**Comment by BreakBB** [comment]
Hey @Duugu could you add `L_UIDROPDOWNMENU_MAXLEVELS` to the bottom of the [.luacheckrc](https://github.com/Questie/Questie/blob/master/.luacheckrc) file?

**Comment by BreakBB** [comment]
Hey @Duugu thanks for this PR :) The next time try to keep the commits together so you add the `L_UIDROPDOWNMENU_MAXLEVELS` to the same branch and therefore to the same Pull Request. But it works nevertheless 👍🏻

**Comment by Duugu** [comment]
> Hey @Duugu thanks for this PR :) The next time try to keep the commits together so you add the `L_UIDROPDOWNMENU_MAXLEVELS` to the same branch and therefore to the same Pull Request. But it works nevertheless 👍🏻

Hey, thanks! 
Apologies for that. :/ This is the first time ever I'm using Github. Have just a basic idea what I am doing. ;)

**Comment by BreakBB** [comment]
No worries @Duugu feel free to reach out on Discord if you need further help on working with GitHub 👍🏻 

Looking forward to more PRs 😉

**Pull request merged**
