### PR TITLE
Fix item Stormwind Seasoning Herbs (2665)

### PR DESCRIPTION
**Pull request by gouletr**
Fixes item [Stormwind Seasoning Herbs (2665)](https://classic.wowhead.com/item=2665/stormwind-seasoning-herbs)
- npcDrops [Felicia Gump (1303)](https://classic.wowhead.com/npc=1303/felicia-gump)
- relatedQuests [Seasoned Wolf Kabobs (90)](https://classic.wowhead.com/quest=90/seasoned-wolf-kabobs)

### CODE REVIEW

**Comment by BreakBB** [comment]
Hey @gouletr with one of the last updates we changed it so that the `vendors` field is also used for quest objectives. So it is no longer required for the work around to add them as `npcDrops`. I might misunderstand you though and the `relatedQuests` is indeed missing!

**Comment by gouletr** [comment]
Ok, I guess the `npcDrops` should be empty then. Do I just set the field to `{}` to make it empty when the correction is applied?

**Comment by BreakBB** [comment]
Since the field has no value in the original `classicItemDB.lua` you can simply remove that line from the corrections. It should stay `nil`

**Comment by gouletr** [comment]
done

**Review by BreakBB — APPROVED** [review]

**Pull request merged**
