### PR TITLE
Update ClassicObjectives.lua

### PR DESCRIPTION
**Pull request by jammergreek**
ruRU.

### CODE REVIEW

**Comment by BreakBB** [comment]
Thanks a lot for these translations @jammergreek !

**Comment by BreakBB** [comment]
Argh. Can you redo this PR and start from the `master` Branch instead of the `QuestieSDB` @jammergreek ? If not, I can do that as well.

**Comment by anon1231823** [comment]
@BreakBB he doesn't understand how to do what you're asking him to do. It might be just easier if you make this change.

**Comment by BreakBB** [comment]
That is totally fine, no worries at all 👍🏻 

Thanks @jammergreek I will take care of getting the changes in <3

**Pull request closed without merging**
