### PR TITLE
QuestieFrame cleanup

### PR DESCRIPTION
**Pull request by BreakBB**
## Proposed changes

- Each `QuestieFrame` stores the entire result of the `QuestieDB:GetQuest` on itself, which is simply not required
- This PR cleans up the `QuestData` table which is added as part of the `icon.data` to each icon
- The only fields currently required are:
  - FadeIcons : boolean
  - HideIcons : boolean
  - level : number
  - requiredLevel : number
  - IsRepeatable : boolean
  - name : string
  - Description : string

This removed quite a lot of bloat data off each `QuestieFrame`

Things to test:

- [ ] Do trivial quests still show correctly?
- [ ] Do objectives of type "event" still show correctly (e.g. escort quests)?
- [ ] Any `nil` errors?
- [ ] Any information missing on map icons/tooltips?

### CODE REVIEW

**Comment by Cabro** [comment]
ALL the map/minimap icon tooltips are gone.

**Comment by BreakBB** [comment]
Not sure what you mean @Cabro 🤔 

image

**Comment by Cabro** [comment]
https://github.com/Questie/Questie/assets/1155017/bf2df953-2183-4a92-b484-983383988548

I also have Dyaxler's fixes for icons from his PR, maybe there's a conflict between these

**Comment by MyTechnoHunter** [comment]
doing a compare right now to see if conflicts..

**Comment by Dyaxler** [comment]
What are you guys talking about? I see nothing wrong. I just merged @BreakBB PR into my local build with my own PR. None of our changes conflict and everything looks good to me. Map and Minimap Icons are all there.

I'm on the Wrath PTR right now if you're looking to test while the server Maintenace is going on.

image

**Pull request merged**
