### PR TITLE
Improve QuestXP performance, clean up code

### PR DESCRIPTION
**Pull request by Laumesis**

### CODE REVIEW

**Comment by Laumesis** [comment]
Rebased on master

**Comment by Laumesis** [comment]
Does intelliJ things support `---@class QuestXP : Module` and related changes in QuestieLoader, which were done in initial QuestXP merge commit?

**Comment by BreakBB** [comment]
@Laumesis it does support custom classes like `Module`, yes.

**Comment by Laumesis** [comment]
> @Laumesis it does support custom classes like `Module`, yes.

Aren't all classes custom? ;P

I mean does it support inheritance?
https://github.com/Questie/Questie/blob/9c2f0d3cddad61b6b530a4773343b8de3ae35bbf/Database/QuestXP/QuestieXP.lua#L2

And does it support generics now? Iirc earlier it didn't.
https://github.com/Questie/Questie/blob/9c2f0d3cddad61b6b530a4773343b8de3ae35bbf/Modules/Libs/QuestieLoader.lua#L20-L23

**Comment by BreakBB** [comment]
> I mean does it support inheritance?

It does:
image

> And does it support generics now? Iirc earlier it didn't.

Looks fine to me :)
image

**Comment by Laumesis** [comment]
Rebased on master

**Comment by Logonz** [comment]
I run VSCode as well and for it to work properly I had to do generics. Not everyone is running IntelliJ ;)
I would also say that the code should be more geared towards vscode rather than IntelliJ because it is a free tool while intelliJ is not.

**Comment by BreakBB** [comment]
I agree to @Logonz I guess I am one of the few people using IntelliJ instead of VS Code

**Pull request merged**
