### PR TITLE
Update esMX.lua

### PR DESCRIPTION
**Pull request by anon1231823**
## Issue references

Fixes #

## Proposed changes

-
-

### CODE REVIEW

**Comment by BreakBB** [comment]
This might happen because of a line ending difference 🤔 How are you creating your local copy of Questie?

**Comment by Cabro** [comment]
I had the exact problem with that file. One of the recent commits related to it messed something up. I had to reclone the repo.

**Comment by anon1231823** [comment]
> This might happen because of a line ending difference 🤔 How are you creating your local copy of Questie?

I have been modifying the file offline

**Comment by BreakBB** [comment]
This commit f77061ec1ea35d2ffdd0ae3e2a660b686aca6b80 changed the line ending from CRLF to LF. We want to use LF for every file though to I changed the line ending back in this commit: 0df5694af0b6d0fb99b7e294333060b080a9d01e

Which editor are you using to edit the files @anon1231823 ?

For Notepad++ [this](https://stackoverflow.com/a/8195860/6419859) will help you to set the line ending to "Unix (LF)" for the file you are editing.

**Comment by anon1231823** [comment]
> This commit [f77061e](https://github.com/Questie/Questie/commit/f77061ec1ea35d2ffdd0ae3e2a660b686aca6b80) changed the line ending from CRLF to LF. We want to use LF for every file though to I changed the line ending back in this commit: [0df5694](https://github.com/Questie/Questie/commit/0df5694af0b6d0fb99b7e294333060b080a9d01e)
> 
> Which editor are you using to edit the files @anon1231823 ?
> 
> For Notepad++ [this](https://stackoverflow.com/a/8195860/6419859) will help you to set the line ending to "Unix (LF)" for the file you are editing.

I'm using Notepad++ and I see it is Unix (LF) now.

**Pull request closed without merging**
