### PR TITLE
Hide "In Search for Thaelrid" from horde once again

### PR DESCRIPTION
**Pull request by Synopt**
## Issue references

Fixes [4080](https://github.com/Questie/Questie/issues/4080)

## Proposed changes

- Remove the correction that shows "In Search of Thaelrid" to all races

### CODE REVIEW

**Comment by BreakBB** [comment]
Hey @Synopt instead of removing the correction from Classic you should add a replacement to the Wotlk quest fixes. Otherwise the quest will falsely show for Classic Era/SoM.

**Comment by Synopt** [comment]
Ah thanks very much - I was wondering if you could point me at the wotlk corrections file? I was looking for it but couldn't find it

**Comment by BreakBB** [comment]
Oh right, that file is atm only available on the `wotlk-branch`. The wotlk changes are not yet in master

**Comment by Synopt** [comment]
I can PR to that branch instead and you can merge when it's ready 👌

**Pull request closed without merging**
