### PR TITLE
Shift+Lclick to link quests

### PR DESCRIPTION
**Pull request by Cabro**
Fixes https://github.com/Questie/Questie/issues/4899

### CODE REVIEW

**Comment by BreakBB** [comment]
Just tested this and you zoom in, when linking a quest from the continent map. Do you think you can find a solution for this?

**Comment by MyTechnoHunter** [comment]
when the chat is closed?

**Comment by BreakBB** [comment]
No, when you link a quest to the chat from the continent map it zooms in and also pastes the quest to the chat. But I think it would be better to not zoom in.

**Comment by MyTechnoHunter** [comment]
game client and version please and thanks.. i cant repro this in wrath.. 
image

**Comment by BreakBB** [comment]
Your screenshot shows a zone map, not a continent map.

**Comment by BreakBB** [comment]
Try linking a quest from here
grafik

**Comment by MyTechnoHunter** [comment]
the zone map is the little one on the right.. the map itself is the main game map (leatrix maps addon makes it not full screen)

**Comment by MyTechnoHunter** [comment]
wup.. i see what you mean.. on the continent level it copies the quest to chat and also clicks into the related area/zone map..  once IN the zone map it then copies fine without changing to a different map..

**Comment by BreakBB** [comment]
Correct.

**Comment by MyTechnoHunter** [comment]
the left click action seems to have always done that though? that part of the code wasnt touched..
we checked for right click, and if not right click we pass down the clicked map uid..
```lua
        else
            if self.UiMapID ~= WorldMapFrame:GetMapID() then
                WorldMapFrame:SetMapID(self.UiMapID);
            end
        end
```

**Pull request merged**
