### PR TITLE
Fixed level check for daily filtering

### PR DESCRIPTION
**Pull request by BreakBB**
## Issue references

Fixes #

## Proposed changes

-
-

### CODE REVIEW

**Comment by MyTechnoHunter** [comment]
is maxlevel required? can you do the dalaran dailies for example at max _profession_ level?

**Comment by BreakBB** [comment]
This is just a minor change, which we don't want to lose.

Currently this will have no effect and for activating the Daily quest filtering we need a lot more testing.

**Comment by BreakBB** [comment]
Also on your actual question: At least wowhead says that for example the Fishing quests require you to be level 70 and no skill level is required.

**Comment by MyTechnoHunter** [comment]
sooo.. not max level in wrath then? being as max = 80?

**Comment by BreakBB** [comment]
Yeah for the fishing stuff it is not. But I am not planning to change the „IsDoable logic“, so that doesn’t matter.

The DailyQuest module is about filtering quests which are not available on _that_ day.

**Pull request merged**
