### PR TITLE
[feature] Major overhaul of Tracker "Sort by Proximity" and TomTom support

### LINKED ISSUE #6655: TomTom not working correctly because QuestieMap:GetNearestQuestSpawn 2nd return value is not a consistent type of id
### Description

QuestieMap:GetNearestQuestSpawn is returning AreaIds in most cases, but returning UiMapIds for completed quests due to using QuestieMap:FindClosestFinisher, which returns a UiMapId. This is causing issues with TrackerUtils:SetTomTomTarget as it is expects an AreaId

---

Quick fix for any readers (only tested in Cata), inside Questie/Modules/Map/QuestieMap.lua

Change line 845
```
local playerZone = HBD:GetPlayerWorldPosition();
```
to
```
local playerZone = C_Map.GetBestMapForUnit("player");
```
AND change line 952
```
return {closestFinisher.x, closestFinisher.y}, closestFinisher.zone, closestFinisher.name
```
to
```
closestFinisher.zone = ZoneDB:GetAreaIdByUiMapId(closestFinisher.zone);
return {closestFinisher.x, closestFinisher.y}, closestFinisher.zone, closestFinisher.name
```

### Questie version

10.7.1

### Game flavor

Cata

### PR DESCRIPTION
**Pull request by BreakBB**
## Issue references

Fixes #6655

## Proposed changes

- Reduce the amount of code needed for distance calculations and introduces the new `DistanceUtils` module
- Fix the distance calculation for objectives and finisher with dungeon spawns

### CODE REVIEW

**Comment by Mattyspatty** [comment]
Getting an exception when attempting to set TomTom target on a specific objective using the tracker r-click menu
```
Message: ...erface/AddOns/Questie/Modules/Libs/DistanceUtils.lua line 119:
   attempt to index local 'quest' (a nil value)
Debug:
   [string "@Interface/AddOns/Questie/Modules/Libs/DistanceUtils.lua"]:119: GetNearestSpawnForQuest()
   [string "@Interface/AddOns/Questie/Modules/Tracker/TrackerMenu.lua"]:72: func()
   [string "@Interface/AddOns/Questie/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:237:
      ...Questie/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:203
   [string "@Interface/AddOns/Questie/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:442:
      ...Questie/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:441
Locals:
quest = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'quest' (a nil value)"
DistanceUtils = <table> {
 private = <table> {
 }
}

```

**Comment by BreakBB** [comment]
Updated the PR. Try again @Mattyspatty <3

**Comment by Mattyspatty** [comment]
Objective issue seems fixed 👍 

Got this other error right after accepting fishing daily in Stormwind. I tried dropping and retaking and did a /rl but was unable to replicate. Pretty sure I wasn't in, nor recently exited, combat.

```
Message: ...erface/AddOns/Questie/Modules/Libs/DistanceUtils.lua line 55:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [string "=[C]"]: pairs()
   [string "@Interface/AddOns/Questie/Modules/Libs/DistanceUtils.lua"]:55: GetNearestObjective()
   [string "@Interface/AddOns/Questie/Modules/Libs/DistanceUtils.lua"]:140: GetNearestSpawnForQuest()
   [string "@Interface/AddOns/Questie/Modules/Tracker/TrackerUtils.lua"]:553:
      ...face/AddOns/Questie/Modules/Tracker/TrackerUtils.lua:538
   [string "@Interface/AddOns/Questie/Modules/Tracker/TrackerUtils.lua"]:866: GetSortedQuestIds()
   [string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:606: Update()
   [string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:365: func()
   [string "@Interface/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua"]:25:
      ...e/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua:17
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
```

**Comment by BreakBB** [comment]
You are just awesome @Mattyspatty ! It's great you are testing this and providing feedback. I'll look into the stack trace and see what could have caused it and where to fix it 👍🏻

**Comment by BreakBB** [comment]
Can you tell (by wowhead link) which quest you accepted?

**Comment by Mattyspatty** [comment]
https://www.wowhead.com/cata/quest=26420/diggin-for-worms

**Comment by BreakBB** [comment]
I found the underlying issue @Mattyspatty and also refactored some more code.

The error you got on that fishing quest was actually a race condition (hence hard for you to reproduce).

**Comment by BreakBB** [comment]
Thanks for coming back to this @Mattyspatty !

I am also quite confident it's working fine. Will wait for some more feedback from beta testers and then release this 👍🏻

**Pull request merged**
