### PR TITLE
Fix bug with untracking quest from tracker menu

### LINKED ISSUE #3233: Untracking a quest via Questie Tracker won't hide its icons
The icons of the quest stay visible on map even user untracks the quest via right click menu on Questie Tracker while `Hide icons of untracked quests` is enabled.

image

v6.7.0

### PR DESCRIPTION
**Pull request by svalentin**
The "untrack quest" menu code and untracking a quest via the "quest log"
code were 2 separate code paths. Merge them into one and fix bug where
icons are not hidden when untracking quest.

Note: the changes display is a bit wonky, but basically the logic inside
`_RemoveQuestWatch` is moved to `QuestieTracker:UntrackQuestId` once we
have a `questId`. That same logic is called in `QuestieTracker:Untrack`,
instead of duplicating the code.

Fixes #3233

### CODE REVIEW

**Comment by Laumesis** [comment]
Just FYI: we are busy trying to get #3111 out finally to fix really old major bug. And trying to limit other changes in codebase until further bugs the #3111 may introduce are mostly known.

**Comment by svalentin** [comment]
That makes sense. Though do take a look at this PR as it helps dedupe some logic and might help!

**Comment by BreakBB** [comment]
Hey @svalentin sorry for letting this wait for so long. Could you check on the merge conflicts? I would be happy to finally merge this!

**Comment by svalentin** [comment]
Hey, I can definitely fix the merge conflicts, but sadly I don't play WoW anymore right now. I won't be able to test it and just make the chances "theoretically".

**Comment by BreakBB** [comment]
That is absolutely no problem for me @svalentin :) If you remove the conflicts I will test the changes and get it merged afterwards 👍🏻

**Comment by BreakBB** [comment]
Hey @svalentin I just had a quick look, resolved the conflicts and tested the fix you suggest. It works like a charm, so I will merge this and want to thank you for this great PR 👍🏻

**Comment by svalentin** [comment]
Awesome!

**Comment by BreakBB** [comment]
@svalentin Thank you for fixing this issue and your patience towards us merging it! <3

**Pull request merged**
